export const userData = [
  {
    name: "Jan",
    "Active User": 2,
  },
  {
    name: "Feb",
    "Active User": 3,
  },
];

export const productData = [
  {
    name: "Jan",
    Sales: 4000,
  },
  {
    name: "Feb",
    Sales: 3000,
  },
  {
    name: "Mar",
    Sales: 5000,
  },
];

export const userRows = [
  {
    id: 1,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 2,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 3,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 4,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 5,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 6,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 7,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 8,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 9,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 10,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/1152994/pexels-photo-1152994.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "jon@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
];

export const productRows = [
  {
    id: 1,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: Math.floor( Math.random()*999 ) + 100,
    status: "active",
    price: `$${Math.floor( Math.random()*999 ) + 100}.00`,
    unitno:12,
    vendor:"Apple",
    aval:true,
    size:90,
    colour:'red',
    material:"Cotton",
    quantity:90,
    discrption:'this is the best product',
    category:"Casual",
    brand:"Sara",
    product_type:"Casual"
  },
  {
    id: 2,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: Math.floor( Math.random()*999 ) + 100,
    status: "active",
    price: `$${Math.floor( Math.random()*999 ) + 100}.00`,
    unitno:12,
    vendor:"Apple",
    aval:true,
    size:90,
    colour:'red',
    material:"Cotton",
    quantity:90,
    discrption:'this is the best product',
    category:"Casual",
    brand:"Sara",
    product_type:"Casual"
  },
  {
    id: 3,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: Math.floor( Math.random()*999 ) + 100,
    status: "active",
    price: `$${Math.floor( Math.random()*999 ) + 100}.00`,
    unitno:12,
    vendor:"Apple",
    aval:true,
    size:90,
    colour:'red',
    material:"Cotton",
    quantity:90,
    discrption:'this is the best product',
    category:"Casual",
    brand:"Sara",
    product_type:"Casual"
  },
  {
    id: 4,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: Math.floor( Math.random()*999 ) + 100,
    status: "active",
    price: `$${Math.floor( Math.random()*999 ) + 100}.00`,
    unitno:12,
    vendor:"Apple",
    aval:true,
    size:90,
    colour:'red',
    material:"Cotton",
    quantity:90,
    discrption:'this is the best product',
    category:"Casual",
    brand:"Sara",
    product_type:"Casual"
  },
  {
    id: 5,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: Math.floor( Math.random()*999 ) + 100,
    status: "active",
    price: `$${Math.floor( Math.random()*999 ) + 100}.00`,
    unitno:12,
    vendor:"Apple",
    aval:true,
    size:90,
    colour:'red',
    material:"Cotton",
    quantity:90,
    discrption:'this is the best product',
    category:"Casual",
    brand:"Sara",
    product_type:"Casual"
  },
  {
    id: 6,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: Math.floor( Math.random()*999 ) + 100,
    status: "active",
    price: `$${Math.floor( Math.random()*999 ) + 100}.00`,
    unitno:12,
    vendor:"Apple",
    aval:true,
    size:90,
    colour:'red',
    material:"Cotton",
    quantity:90,
    discrption:'this is the best product',
    category:"Casual",
    brand:"Sara",
    product_type:"Casual"
  },
  {
    id: 7,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: Math.floor( Math.random()*999 ) + 100,
    status: "active",
    price: `$${Math.floor( Math.random()*999 ) + 100}.00`,
    unitno:12,
    vendor:"Apple",
    aval:true,
    size:90,
    colour:'red',
    material:"Cotton",
    quantity:90,
    discrption:'this is the best product',
    category:"Casual",
    brand:"Sara",
    product_type:"Casual"
  },
  {
    id: 8,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: Math.floor( Math.random()*999 ) + 100,
    status: "active",
    price: `$${Math.floor( Math.random()*999 ) + 100}.00`,
    unitno:12,
    vendor:"Apple",
    aval:true,
    size:90,
    colour:'red',
    material:"Cotton",
    quantity:90,
    discrption:'this is the best product',
    category:"Casual",
    brand:"Sara",
    product_type:"Casual"
  },
  {
    id: 9,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: Math.floor( Math.random()*999 ) + 100,
    status: "active",
    price: `$${Math.floor( Math.random()*999 ) + 100}.00`,
    unitno:12,
    vendor:"Apple",
    aval:true,
    size:90,
    colour:'red',
    material:"Cotton",
    quantity:90,
    discrption:'this is the best product',
    category:"Casual",
    brand:"Sara",
    product_type:"Casual"
  },
  {
    id: 10,
    name: "Apple Airpods",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    stock: Math.floor( Math.random()*999 ) + 100,
    status: "active",
    price: `$${Math.floor( Math.random()*999 ) + 100}.00`,
    unitno:12,
    vendor:"Apple",
    aval:true,
    size:90,
    colour:'red',
    material:"Cotton",
    quantity:90,
    discrption:'this is the best product',
    category:"Casual",
    brand:"Sara",
    product_type:"Casual"
  },
];
